### ISSUE TITLE
Initial Vehicle Route that ignores constraints

### ISSUE THREAD

**Issue by demonicmetalcs** [jsprit/jsprit#152]
If i add an initial route that contains an job that doesn't meet an constraint that Vehicle will not get any other jobs.
Is this by design?
and is there a way around this?

example
the vehicle has a start time om 8
the initial route has 1 job that starts at 9
and we have a job to be planed.

it takes the vehicle 2 to get to the initial route job but i would like it to ignore this and just start planning the job to be planed after the job of .

**Comment by oblonski** [comment]
I do not understand your example. Could you be a bit more precise?

**Comment by demonicmetalcs** [comment]
say we have 2 jobs,
job A end job B
and 1 vehicle

the vehicle has an earliest start of 8
job A we add to the vehicle initial route with a time window of 8 till 9
but it the vehicle has to travel there that would take him 2 so he could be there as early as 10,that would not meet the time constraint.
at this point the algorithm invalidates all the routes for that vehicle.

I would like to override this and put job A at 8 and continue planning job B

**Comment by demonicmetalcs** [comment]
so if we put something in the initial route that does not meet the constraints.
that vehicle will not get anything planned.
but we would like the initial route to ignore the constarints.

**Comment by PGWelch** [comment]
This would be a good feature to have - however you could probably do this as a preprocessing step before running jsprit by checking the time window against the available time & travel time and expanding it so the job is just feasible. Of course this might not work for more complex scenarios. 
		
        
		Philip WelchOpen Door Logistics LimitedSpecialists in open source solutions for transport logistics.Email: info@opendoorlogistics.comLinkedin:  http://uk.linkedin.com/in/welchphilipSkype: opendoorlogisticsTel:  +44 (0) 20 8144 4009Website:  http://www.opendoorlogistics.com
		 ---- On Mon, 23 Mar 2015 08:22:57 +0000  notifications@github.com  wrote ----so if we put something in the initial route that does not meet the constraints.
that vehicle will not get anything planned.
but we would like the initial route to ignore the constarints.

**Comment by oblonski** [comment]
Ok. I understand. But probably you do not want jsprit to ignore all constraints, i.e. ignore time window but still check capacity constraints. Thus, I do not see a consistent and straightforward way to achieve this. However - as Phil wrote - you can always modify the constraints of job A individually, e.g. switch off time windows when building job A. There are a few reasons why this is a not so bad approach: a) you need to build a new vrp anyway and b) obviously the time window of job A is actually not hard anymore, since you would accept a delay of 1 hour. 
And you can still enforce that job A need to be served first. Look at what is suggested here: http://stackoverflow.com/questions/28894695/impose-order-in-jsprit-with-hardactivityconstraint/28959110#28959110
