### ISSUE TITLE
Question: Optimize for fix number of vehicles evenly

### ISSUE THREAD

**Issue by balage1551** [jsprit/jsprit#163]
Hello,

I am amazed with your library for VRP-related problems. They are well designed and easy to use.

However, I have a problem to solve and being new with your API, I am not sure how to solve it. 

My problem is a m-VRP-TW (a multiple vehicle, pick and delivery routing problem, with time windows). The examples I found in your project covers this problem well, but they all seem to optimize for vehicle number, meaning it will use no more vehicles than they should. However, I need to find a solution, when all the vehicles (within sanity bounds) are used and are utilized as evenly as it could be managed.

Here is an over-simplified example: let's have 100 tasks (let's ignore tw for the sake of simplicity) requiring 1 time unit each and having 10 vehicles with time unit "capacity" of 20.
The solution in the examples would distribute the tasks for 5 vehicles (maybe 6) each having approximatly 20 tasks. 
OTOH, what I need is a solution where all 10 vehicles are in use having approximatly 10 task each.

I feel somehow the cost heuristics should be tweaked, but the code base is too big to find the right way.

Thanks for your help,
Balage

**Comment by PGWelch** [comment]
Could you try setting the fixed cost for the vehicles to zero? With regard to balancing work evenly, this is hard. If you tried adding a quantity constraint - for example one for each stop and setting the total capacity in the vehicles in your solution to only a bit over the number of stops, with equal capacity on each vehicle, then you could force a rough balance of number of jobs? 
		
        
		Philip WelchOpen Door Logistics LimitedSpecialists in open source solutions for transport logistics.Email: info@opendoorlogistics.comLinkedin:  http://uk.linkedin.com/in/welchphilipSkype: opendoorlogisticsTel:  +44 (0) 20 8144 4009Website:  http://www.opendoorlogistics.com
		 ---- On Sat, 13 Jun 2015 13:03:00 +0100  notifications@github.com  wrote ----Hello,
I am amazed with your library for VRP-related problems. They are well designed and easy to use.
However, I have a problem to solve and being new with your API, I am not sure how to solve it. 
My problem is a m-VRP-TW (a multiple vehicle, pick and delivery routing problem, with time windows). The examples I found in your project covers this problem well, but they all seem to optimize for vehicle number, meaning it will use no more vehicles than they should. However, I need to find a solution, when all the vehicles (within sanity bounds) are used and are utilized as evenly as it could be managed.
Here is an over-simplified example: let's have 100 tasks (let's ignore tw for the sake of simplicity) requiring 1 time unit each and having 10 vehicles with time unit "capacity" of 20.
The solution in the examples would distribute the tasks for 5 vehicles (maybe 6) each having approximatly 20 tasks. 
OTOH, what I need is a solution where all 10 vehicles are in use having approximatly 10 task each.
I feel somehow the cost heuristics should be tweaked, but the code base is too big to find the right way.
Thanks for your help,
Balage

**Comment by balage1551** [comment]
Thanks Philip for the quick answer.
I checked the fixed cost and it has been set to 0 already.
For the other part of your answer, I have to understand it deeply. It could be the key, but have some problems to resolve, My example was simplified, but the real jobs require different time and the travel is different too, so by "distribute roughly evenly" I mean rather evenly by execution time then evenly by number. 
I tried an other tool too, and ran into this problem too, so now I wonder whether I want something out of the problem domain. There we found that the initial solution was already the tight, unbalanced one and the algorith wasn't able to diverge enough.

**Comment by PGWelch** [comment]
Balancing by execution time is difficult, as balancing by travel time is very difficult. If possible and assuming your end client has a pool of regular drivers, I would try and persuade them to just rotate the shortest route between drivers on different days (so the drivers take turns on getting the short route). 

If this doesn't work, doing it with jsprit is hard, because naive approaches to balancing the routes - for example taking the shortest route and rearranging its stops to make it less efficient - are obviously very undesirable. Really you want to balance travel time, without making the total travel time much worse, but you accept its going to get a little bit worse. I think your best approach would be to try to write some custom insertion / move code using jsprit that makes the least costly moves from shorter routes to longer routes. So you do a combination of optimise using normal jsprit, balance using some custom code, and maybe repeat this? 


Stefan - the author of jsprit - may have some better suggestions?


Writing custom insertion / move code would be relatively time consuming and complex. If you're lucky you may be able to do this by writing a SoftActivityConstraint rather than re-writing the insertion code, but without spending a lot of time looking at this problem, its difficult to say.


You'd also have to watch out for cases where the geographic distribution of stops means you have a short route that really should be a short route. For example you have two towns A and B and a depot which sits in between the two. You have lots of work in town A and some work in town B. The work in town B can be served by a single vehicle in about 3/4 of a day - so the route is always short. The work in town A is served by many vehicles which are always full. Towns A and B are not that close to each other, so it doesn't make sense for a vehicle to try serving A and B in the same day.

Philip WelchOpen Door Logistics LimitedSpecialists in open source solutions for transport logistics.


Email: info@opendoorlogistics.com
Linkedin:  http://uk.linkedin.com/in/welchphilip
Skype: opendoorlogistics
Tel:  +44 (0) 20 8144 4009
Website:  http://www.opendoorlogistics.com






---- On Sat, 13 Jun 2015 22:23:47 +0100 balage1551&lt;notifications@github.com&gt; wrote ---- 

Thanks Philip for the quick answer.
 I checked the fixed cost and it has been set to 0 already.
 For the other part of your answer, I have to understand it deeply. It could be the key, but have some problems to resolve, My example was simplified, but the real jobs require different time and the travel is different too, so by "distribute roughly evenly" I mean rather evenly by execution time then evenly by number. 
 I tried an other tool too, and ran into this problem too, so now I wonder whether I want something out of the problem domain. There we found that the initial solution was already the tight, unbalanced one and the algorith wasn't able to diverge enough.

**Comment by oblonski** [comment]
@I am amazed with your library for VRP-related problems. They are well designed and easy to use.

Hmm. That is music to my ears :).

Your problem is basically related to a min-max travel time problem, i.e. the objective is not to minimize total travel time but to minimize the maximum of the individual route's travel time. Phil is correct, it cannot be done with jsprit yet.
My suggestion is that you force the employment of your drivers by simple constraints. For example, restrict the total working time of your drivers (for example to 7 hours). If you are still unhappy with the results, you can reduce this value and/or you can increase the service time of your services (e.g. increase them by a factor of 2). Thus, find a combination of values such that you can just serve all your customers (i.e. unassigned job list is empty) with all your drivers. This way you might end up with a reasonable and balanced solutions.

**Comment by balage1551** [comment]
Hello, Stefan!

Thanks for the great hints how to solve my problem. The iterative approach, where I operate with the vehicle times works well, it gives acceptable solutions, almost. :-)
The two problem I still have to solve: 
1) How could I connect a pickup-delivery jobs? In real world, they goes in pair, and I have to not only force them to be made by the same vehicle, but I have even to force them to be performed after each other. To look on them is another way: they are really a single job with different start and end location. 
2) The algorithm tends to skip jobs farther away. Even when there is quite enough time capacity to serve them. I suspect it is correlated with the cost function and leaving them out would result a better solution than including. If this is the case, I only have to give high penalty for unassigned jobs, but can't find where to do this. Could you give some hint?

Thanks,
Balage

**Comment by oblonski** [comment]
@1) Use [Shipment](https://github.com/jsprit/jsprit/blob/master/jsprit-core/src/main/java/jsprit/core/problem/job/Shipment.java) rather than Service. 

@2) Try to provide your own [SolutionCostCalculator](https://github.com/jsprit/jsprit/blob/master/jsprit-core/src/main/java/jsprit/core/problem/solution/SolutionCostCalculator.java) and increase the penalty for unassigned jobs. You can set it with [Jsprit.Builder](https://github.com/jsprit/jsprit/blob/master/jsprit-core/src/main/java/jsprit/core/algorithm/box/Jsprit.java#L217). I suggest you to study how the [default SolutionCostCalculator](https://github.com/jsprit/jsprit/blob/master/jsprit-core/src/main/java/jsprit/core/algorithm/box/Jsprit.java#L545) looks like. Please note, if you want to set your own SolutionCostCalculator you need to use the latest snapshot, since there was [this issue](https://github.com/jsprit/jsprit/issues/158) which is solved now (but not yet in the latest release).

**Comment by balage1551** [comment]
Hello again!
Following your hints, I created an external looping which by a narrowing approximation finds the minimal vehicle time window in which the tasks could be distributed, and this enforces a close to even distribution. (I will gladly give the code too, after it reaches maturity from its current prototype level.)

Now I am integrating JSprit into our project and have a question.
I would like to build up the Algorithm from Java code instead of an XML file. I started to examine the readers (readAndCreateAlgorithm), but it is rather complex and there is a time pressure. So I wonder if there is any example where the algorithm is built-up from code to start from?

**Comment by oblonski** [comment]
Here is how it works:

https://github.com/jsprit/jsprit/blob/master/jsprit-examples/src/main/java/jsprit/examples/ConfigureAlgorithmInCodeInsteadOfPerXml.java

or just read the latest post here to use Jsprit.createAlgorithth ...

https://github.com/jsprit/jsprit/blob/master/WHATS_NEW.md

Am 22/07/15 um 12:11 schrieb balage1551:

**Comment by balage1551** [comment]
Thanks for the quick answer. I've already done the conversation. :-)
Also I made some extension for the SolutionPrinter class: added a counterpart of the print* methods which got an additional parameter: a PrintWriter, so now I could print the solution into anything that could be wrapped into a PrintWriter (pl. System.out, new PrintWriter(new StringWriter()), etc.)
If you think so, I would gladly send it and could be added to the next release.

**Comment by balage1551** [comment]
One more question:
How hard would it be to add the cost calculator to receive the current load when calculating time cost?
I have a vehicle where I should use different speed for unloaded and loaded runs.

As far as I see, the time calculation is done in one of the BackwardTransportTime and ForwardTransportTime interface implementations. 

What exactly these two interfaces used for? What is Backward and Forward? May it be the one I am looking for and do I only need to implement a calculator with different implementation for the two?

**Comment by oblonski** [comment]
Can we close this here in the issue tracker and move this discussion to
the mailing list?

https://groups.google.com/forum/#!forum/jsprit-mailing-list

Am 22/07/15 um 17:34 schrieb balage1551:

**Comment by balage1551** [comment]
Sure. :-)

**Comment by oblonski** [comment]
Btw: According to your extensions to the SolutionPrinter, can you make a pull request? Then we can discuss your extensions and merge it into the master branch.
