### ISSUE TITLE
driver breaks

### ISSUE THREAD

**Issue by oblonski** [jsprit/jsprit#170]
see discussion here: https://groups.google.com/forum/#!topic/jsprit-mailing-list/x-ed1DcTyJ4

**Comment by oblonski** [comment]
in branch https://github.com/jsprit/jsprit/tree/driver-breaks

**Comment by oblonski** [comment]
- [ ] cluster strategy cannot deal with variable locations of activity, i.e. jobs need locations
- [ ] remove unneccessary breaks at end of route
- [ ] further testing with services
- [ ] test with shipments
- [ ] test with mixed problems
- [ ] breaks with INFINITE fleet do not work - solve this or throw unsupported operation exception

**Comment by oblonski** [comment]
relates to #99

**Comment by oblonski** [comment]
Do we need multiple predefined driver breaks?

**Comment by oblonski** [comment]
Do we need driver breaks with predefined locations?

**Comment by oblonski** [comment]
examples:
https://github.com/jsprit/jsprit/blob/28dcb2fb567ee653f69977831aa395f19af649ff/jsprit-examples/src/main/java/jsprit/examples/VariableStartAndWaitingTimeExample.java

and

https://github.com/jsprit/jsprit/blob/28dcb2fb567ee653f69977831aa395f19af649ff/jsprit-examples/src/main/java/jsprit/examples/BreakExample.java

**Comment by nottsmcr** [comment]
Hi. I have discovered a bug in the way driver breaks are being handled and it's quite unusual so was difficult to spot. 

Sometimes, when using a custom distance/time matrix, it is possible for the break to actually be assigned the vehicle starting location even when it is being taken in the middle of a route. It's not clear to me what is causing this because it often doesn't appear, and I haven't been able to pin down the series of events that leads to this. It's not easily repeated on a standard dataset - it appears to be random chance, so perhaps it is something to do with the order that the job happens to be added to the route which somehow can trigger it to be a non-variable location.

The vehicle is built as follows:

VehicleImpl vehicle = VehicleImpl.Builder.newInstance(Integer.toString(i)).setEarliestStart(driverStartTime).setLatestArrival(driverEndTime).setStartLocation(Location.newInstance("0")).setType(type1).setBreak((Break) Break.Builder.newInstance("lunch").setTimeWindow(TimeWindow.newInstance(lunchStartTime,lunchEndTime-40)).setServiceTime(lunchLength).build()).build();

vrpBuilder.addVehicle(vehicle);

The problem can be identified when there is a non-zero driving time BOTH before and after the lunch break. Expected behaviour is only one of them having zero time. I have verified that, in this instance, the driving time to the lunch break is equal to the time to travel from previous location to the vehicle starting location. Similarly, the following journey is then equivalent to travelling from the starting location to the location of the next job.

**Comment by oblonski** [comment]
Irrr. This should not happen. Could you open an extra issue for that? It is a pitty that it is not easily reproducable ;(.

**Comment by oblonski** [comment]
and thanks for reporting

**Comment by nottsmcr** [comment]
No prob at all. I'll spend a little more time today seeing if I can find any pattern to it before raising so you can hopefully get a repeat. The interesting thing is that in three instances, the location immediately after the break was the same, but the problem vanished when it was a different location. 

I should add that the min waiting time solver is being used, with the algorithm override you wrote, that adds a cost to routes that do not include a break. With the next location in the route appearing (at least in some way) to be an influence, I wonder whether this happens when a break is initially in the route and then pulled back out.

**Comment by oblonski** [comment]
If you found a way to reproduce the bug, it would be great! Thanks.

**Comment by oblonski** [comment]
driver breaks are in latest release. see also: https://github.com/jsprit/jsprit/issues/211
