### ISSUE TITLE
Time window not satisfied in simple case

### ISSUE THREAD

**Issue by maxgrv** [jsprit/jsprit#201]
Hi there, we are trying to use JSprit to solve a VRP with Time Windows problem. We are encountering a strange issue and we have been able to reproduce it in a very simple unit test:

Consider a simple problem with just one vehicle with earliest start at 8.0 and latest arrival = 18.00 and one service job, with time window (10.0, 10.0) and duration 1.0. 

The solution we get has serviceStartTime 8.0 and serviceEndTime = 11.0. 

I have attached to this issue the problem+solution XML output which show clearly the problem.

We think we are missing something stupid, but we cannot see where.
I can post the unit test code if necessary. We use JSprit 1.6.1.

Thanks in advance.

[problem-with-solution.txt](https://github.com/jsprit/jsprit/files/66340/problem-with-solution.txt)

**Comment by oblonski** [comment]
Hi,
Great you try to use jsprit.
The solution looks fine for me. Note that 8.0 is not the serviceStartTime, but the arrival time at the activity. Due to your time-window the service is only allowed to start at 10.0. Thus the vehicle needs to wait 2 time-units before service can start. Since it takes 1 time-unit, service end time and thus the departure time from there is 11.0.

**Comment by oblonski** [comment]
Let me know if this makes sense and whether I can close this here.

**Comment by maxgrv** [comment]
Thanks Stefan, that makes sense. Sorry for the stupid question :) and
congratulations, JSprit is fantastic!

**Comment by oblonski** [comment]
Thanks for your kind words.
