### ISSUE TITLE
break time window not satisfied

### ISSUE THREAD

**Issue by maxgrv** [jsprit/jsprit#202]
We noticed a strange behavior of jsprit if we set a time-window on a flexible-location break. The time window very often is not satisfied.

We have been able to reproduce this bug in a simple problem with mock coordinates. I have attached an [XML dump](https://github.com/jsprit/jsprit/files/77268/breakTimeWindows1.txt) to this issue.

In the XML break is not dumped completely, but it has been setup as follows:

{[id=PRANZO_R][name=no-name][type=break][location=null][capacity=[noDimensions=1][[dimIndex=0][dimValue=0]]][serviceTime=1.0][timeWindow=[start=14.0][end=15.0]]}

We are using the latest commit (hash: b012730) of the multiple time windows branch.

**Comment by oblonski** [comment]
With regard to your problem, could you please set waiting time costs for your vehicle (use this method) to a value higher than zero. For example, set it to the value of 'costPerTransportTime'. The logic behind this is the following: If waitingCosts is zero then the algorithm does not care when to make the break because waiting for a break does not imply any additional costs. If waitingCosts > 0 the algorithm does care since making a break before the preferred time window imposes additional waiting costs. Note that if waiting costs are higher than transport costs, the algorithm is likely to end up with strange results since then it always tries to avoid waiting no matter of transportation costs.
Let me know if this solves your problem. 

PS: Probably this needs to be documented somewhere.
